---

- name: Create a PID directory
  file:
    state: directory
    path: "{{ mongo_process_pid|dirname }}"
    owner: "{{ mongo_user }}"
    group: "{{ mongo_user }}"
    mode: 0755
  when: mongo_process_pid != ''

- name: Create a PID file
  file:
    state: touch
    path: "{{ mongo_process_pid }}"
    owner: "{{ mongo_user }}"
    group: "{{ mongo_user }}"
    mode: 0755
  when: mongo_process_pid != ''

- name: Change a systemD service
  template:
    src: mongo.service.j2
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 1777
  with_items:
    - /etc/systemd/system/multi-user.target.wants/mongod.service
    - /usr/lib/systemd/system/mongod.service
  when: mongo_process_pid != ''

- name: Daemon-Reload
  systemd: daemon_reload=yes
