---

- name: Clone non-auth config for start the cluster
  template:
    src: mongodb_init.conf.j2
    dest: /etc/mongo/mongod.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reboot mongo
    - wait for starting process on localhost

- name: Create admin user
  mongodb_user:
    database: admin
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    update_password: "{{ mongo_update_password }}"
    roles: "{{ item.roles }}"
    login_port: "{{ mongo_net_port }}"
  with_items:
    - {
      name: "{{ mongo_admin }}",
      password: "{{ mongo_admin_password }}",
      roles: "userAdminAnyDatabase"
    }

- name: Create root user
  mongodb_user:
    database: admin
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    update_password: "{{ mongo_update_password }}"
    roles: "{{ item.roles }}"
    login_port: "{{ mongo_net_port }}"
  with_items:
    - {
      name: "{{ mongo_root }}",
      password: "{{ mongo_root_password }}",
      roles: "root"
    }  

- name: Create backup user
  mongodb_user:
    database: admin
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    update_password: "{{ mongo_update_password }}"
    roles: "{{ item.roles }}"
    login_port: "{{ mongo_net_port }}"
  with_items:
    - {
      name: "{{ mongo_backup }}",
      password: "{{ mongo_backup_password }}",
      roles: "backup,clusterMonitor"
    }  

- name: Move back original config of mongod
  template:
    src: mongod.conf.j2
    dest: /etc/mongo/mongod.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reboot mongo
    - wait for starting the process
